### ISSUE TITLE
Can't "show"

### ISSUE THREAD

**Issue by alexfrad** [kotfire/jquery-clockpicker#3]
Hi, i've been using this for a while and recently i had to change something so the clockpicker would show when I press a button. But nothing happen when i click on it. I've already use other functions, like 'done' and it's working perfectly. But using the same syntax, i can't 'show'.
Here's how i call it: 
`$('#clock_on_time').jqclockpicker('show'); //Nothing happen`
This is what i do for 'done:
`$("#clock_on_time").jqclockpicker('done'); //Do what it should do` 

In fact the thing that i want to do is to open the clockpicker when clicking on a button and not when i click/focus on the input.

--UPDATE--
From what i can see it has to do with self.hide()  --Line 540 at src/jquery-clockpicker.js
Since the target is not the input it's hiding it.

Thanks for your help!

**Comment by kotfire** [comment]
Hi,

I've updated basic example with show/hide programmatically. Could you check it and tell me if that fits your case of use?

> In fact the thing that i want to do is to open the clockpicker when clicking on a button and not when i click/focus on the input.

I think adding an option `showOn` could be a good approach, but don't expect it to be released soon. I need to find some free time to work on it.

**Comment by alexfrad** [comment]
Finally it was my mistake, looks like the only way to trigger this kind of action is to get the object of the clockpicker at initialisation. I thought the show method would work like the others but since in the function it checks the event it doesn't work the same way.
`clockOnInput = $("#clock_on_time").jqclockpicker( options});
//In my events: 
clockOnInput.jqclockpicker('show');
`
Anyway thanks for your answer!
